In [1]:
import numpy as np
students = np.random.randint(50,101,size=(50,5))
students

array([[ 79,  53,  92,  94,  55],
       [ 65,  70,  81,  62,  76],
       [ 77,  52,  96,  60,  57],
       [ 94,  73,  89,  50,  83],
       [ 57,  88,  90,  73,  74],
       [ 71,  61,  50,  98,  66],
       [ 66,  54,  79,  58,  91],
       [ 79,  66,  61,  57,  84],
       [ 60,  52,  73,  90,  89],
       [ 60,  57,  72,  79,  91],
       [ 90,  84,  73,  88,  71],
       [ 84,  83,  81,  75,  65],
       [ 60,  99,  55,  73,  65],
       [ 91,  99,  94,  93,  50],
       [ 53,  90,  93,  99,  53],
       [ 53,  70,  96,  54,  89],
       [ 87,  52,  53,  89,  69],
       [ 67,  69,  56,  51,  87],
       [ 56,  91,  53,  90,  71],
       [ 59,  71,  50,  84,  77],
       [ 98,  77,  73,  78,  79],
       [ 76,  85,  98,  56,  63],
       [ 88,  85,  94,  53,  91],
       [ 99,  77,  81,  93,  71],
       [ 51,  64,  94,  55,  80],
       [ 75,  85,  99,  80,  72],
       [ 97,  50,  59,  93,  83],
       [ 75,  67,  96,  55,  57],
       [ 99,  54,  71,  57,  95],
       [ 55,  

In [2]:
students[0,0]
students[:1,:]
students[:1] #前一個學生
students[:2] #前2個學生
students[-5:] #最後5個學生

array([[ 64,  71,  85, 100,  54],
       [ 95,  90,  74,  98,  54],
       [ 53,  65,  99,  76,  50],
       [ 55,  70,  83,  88,  61],
       [ 71,  80,  67,  94,  77]])

In [5]:
print(students[0,0])
students[:1,:]

79


array([[79, 53, 92, 94, 55]])

In [7]:
print(students[:,0]) #第一科所有分數
students[:,-1] #最後一科所有分數

[79 65 77 94 57 71 66 79 60 60 90 84 60 91 53 53 87 67 56 59 98 76 88 99
 51 75 97 75 99 55 67 78 62 63 58 73 62 78 57 65 61 89 81 98 57 64 95 53
 55 71]


array([ 55,  76,  57,  83,  74,  66,  91,  84,  89,  91,  71,  65,  65,
        50,  53,  89,  69,  87,  71,  77,  79,  63,  91,  71,  80,  72,
        83,  57,  95,  51,  50,  84,  77,  67,  89,  91,  93,  79,  75,
        51,  59, 100,  82,  82,  57,  54,  54,  50,  61,  77])

In [9]:
print(np.sum(students[:1])) #第一個學生總分
np.sum(students[:2],axis=1) #前2個學生的總分 
np.sum(students,axis=1) #全班每位學生的總分
np.mean(students,axis=0) #每一科全班的平均
np.median(students,axis=0) #每一科全班的中位數

373


array([69. , 74.5, 81. , 75.5, 74.5])